[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

[[plugin.prepend_fetchers]]
id   = "git"
name = "*/"
run  = "git"

# Opener definitions
[opener]
baobab = [
	{ run = 'baobab "$1"', desc = "Baobab", orphan = true, for = "linux" },
]

reveal = [
	{ run = "xdg-open %d1", desc = "Reveal gigi" },
]

# Open rules - add baobab as an option for directories in open --interactive
[open]
prepend_rules = [
	{ name = "*/", use = [ "edit", "open", "baobab" ] },
]

# keymap.toml
[[mgr.prepend_keymap]]
on   = "+"
run  = "plugin zoom 1"
desc = "Zoom in hovered file"

[[mgr.prepend_keymap]]
on   = "-"
run  = "plugin zoom -1"
desc = "Zoom out hovered file"
